# Generated by Django 5.1 on 2025-02-15 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store_Structure",
            fields=[
                (
                    "store_structure_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("store_name", models.CharField(max_length=100)),
                ("floor", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
                ("space", models.CharField(max_length=100)),
                (
                    "store_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
