# Generated by Django 5.1 on 2025-01-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("storeview", "0002_delete_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store_Structure",
            fields=[
                (
                    "store_structure_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("store_name", models.CharField(max_length=100)),
                ("floor", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
                ("space", models.CharField(max_length=100)),
            ],
        ),
    ]
