# Generated by Django 5.1 on 2024-12-12 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="item_category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="tag",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="tag_type",
            fields=[
                ("tag_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_type_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="item",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=100)),
                ("item_date", models.DateTimeField()),
                ("item_lost_location", models.CharField(max_length=100)),
                ("item_description", models.TextField()),
                (
                    "item_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("item_status", models.BooleanField(default=False)),
                ("item_founder", models.CharField(max_length=100)),
                (
                    "item_category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.item_category",
                    ),
                ),
                (
                    "item_tag_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.tag"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tag",
            name="tag_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.tag_type"
            ),
        ),
    ]
