# Generated by Django 5.1 on 2025-01-09 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="item_message",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField(max_length=500)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.item"
                    ),
                ),
            ],
        ),
    ]
