# Generated by Django 5.1 on 2025-01-16 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_alter_item_item_founder_item_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="items.item_category"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_tag_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="items.tag"
            ),
        ),
    ]
