# Generated by Django 5.1 on 2025-01-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="item_message",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
            preserve_default=False,
        ),
    ]
