# Generated by Django 5.1 on 2025-01-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_remove_item_item_tag_id_item_item_tag_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="tag_type",
        ),
        migrations.CreateModel(
            name="item_keyword",
            fields=[
                ("keyword_id", models.AutoField(primary_key=True, serialize=False)),
                ("keyword", models.CharField(max_length=200)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.item"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="tag_type",
        ),
    ]
