# Generated by Django 5.1 on 2025-01-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_remove_tag_tag_type_item_keyword_delete_tag_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="item_tag_id",
        ),
    ]
