# Generated by Django 5.1 on 2025-01-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_remove_item_item_tag_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_keyword",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="item_keyword",
        ),
    ]
