# Generated by Django 5.1 on 2025-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_item_item_keyword_delete_item_keyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_keyword",
            field=models.CharField(max_length=600),
        ),
    ]
