# Generated by Django 5.1 on 2025-02-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_alter_item_item_keyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_keyword",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
