# Generated by Django 5.1 on 2025-02-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0010_add_item_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="ai_generated_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
