# Generated by Django 5.1 on 2025-01-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="account_id",
        ),
        migrations.AddField(
            model_name="user",
            name="is_store",
            field=models.BooleanField(default=False, verbose_name="Store account"),
        ),
    ]
