# Generated by Django 5.1 on 2025-01-09 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_account_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": (("Store", "View Store content"),)},
        ),
    ]
