# Generated by Django 5.1 on 2025-01-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="is_store",
            field=models.BooleanField(default=False, verbose_name="store status"),
        ),
    ]
