# Generated by Django 5.1 on 2025-01-09 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userview", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
