#インストールされているバージョンによって末尾の数字調整
runtime: python312
env_variables:
  DJANGO_SECRET_KEY=django-insecure-your-secret-key-here
  ALLOW_ACCESS_HOSTS=localhost,127.0.0.1,*
# 下記は 設定用ディレクトリ.wsgi:application のように記述
entrypoint: gunicorn -b :$PORT config.wsgi:application

# 下記はhttpでアクセスがあった際、httpsにリダイレクトするための記述
handlers:
 - url: .*
   secure: always
   script: auto